services:
  - type: web
    name: explorewallah-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_VERSION
        value: 20.17.0
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: explore_wallah_secret_jwt_key_2026
      - key: JWT_REFRESH_SECRET
        value: explore_wallah_refresh_secret_key_2026
